name: package-and-deploy
on:
  push: # 在代码提交时自动触发
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for package
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: package
        run: |
          mvn --batch-mode package
      - name: Set env
        run: |
          echo "PACKAGE_JAR=$(ls -l target | grep '.jar$' | awk '{print $NF}')" >> $GITHUB_ENV
          echo $PACKAGE_JAR
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "target/${{ env.PACKAGE_JAR }}"
          target: "/home/${{ secrets.USERNAME }}/jar"
      - name: executing remote ssh commands
        # 使用appleboy/ssh-action@master来执行命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/jar
            mv target/${{ env.PACKAGE_JAR }} ${{ env.PACKAGE_JAR }}
            rm -rf target
            echo ${{ env.PASSWORD }} | sudo -S service my-java-hualihushao restart
